apiVersion: v1
kind: Service
metadata:
  name: userapi
spec:
  selector:
    app: userapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: registry.gitlab.com/keisuke.sakasai/userapi:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
